### ISSUE TITLE
Unknown status error without any information about the status error

### ISSUE THREAD

**Issue by littleskunk** [storj/node-libstorj#65]
As developer I would like to understand what I did wrong. At the moment I get only the response `Error: Unknown status error` https://github.com/Storj/node-libstorj/blob/eb03a2229a8ddfbfb545da62e4e5aa3d193200ab/binding.cc#L71

That is a useless error message. I need at least the error code in order to fix it.

**Comment by littleskunk** [comment]
I found a list of error code here: https://github.com/Storj/service-error-types/blob/f6805c50ba5a28b1293a3d4c1b837354061fa604/index.js

I will create a new issue for the missing error codes.

**Comment by hunterInt** [comment]
any update here?

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
