### ISSUE TITLE
Unsupported protocol 

### ISSUE THREAD

**Issue by xikimay** [storj/node-libstorj#67]
When trying to getBuckets() and after authentication (with encryption_key/key) I get this message:
"Unsupported protocol"
I'm on OSX High Sierra, with the last version of curl

**Comment by bryanchriswhite** [comment]
@xikimay, can you share the code you're running?

**Comment by bryanchriswhite** [comment]
And can you elaborate on "after authentication"?

**Comment by xikimay** [comment]
Yes of course
First I "Authenticate", create the Env Object using the key and encryptionKey param.
```
   encryptionKey = Storj.mnemonicGenerate(128)
            var storj = new Storj.Environment({
                key: postgresTask.encryption_privateKey,
                encryptionKey: encryptionKey
            })
```

And then I simply call getBuckets()

```
storj.getBuckets(function(err, result) {
      if (err) throw err
         console.log(result)
 })
```

**Comment by xikimay** [comment]
Also when logging with the normal auth as shown in the example it works:

```
const storj = new Environment({
  bridgeUrl: 'https://api.storj.io',
  bridgeUser: 'user@domain.com',
  bridgePass: 'password',
  encryptionKey: 'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about',
  logLevel: 4
});
```

**Comment by julianapeace** [comment]
Any updates on this issue?

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
